### ISSUE TITLE
Tag error

### ISSUE THREAD

**Issue by LuNiKoFf** [cinema6/vast-player#4]
Hi,

I tried this tag : https://ads.stickyadstv.com/vast/vpaid-adapter/2119122 and it worked perfectly.

But, when I try this tag : https://vid.springserve.com/vast/120164 it doesn't work at all.

I have this error : 
```
Uncaught TypeError: q[b] is not a function
    at https://cdn.jsdelivr.net/vast-player/latest/vast-player.min.js:2:15076
    at Array.map (native)
    at https://cdn.jsdelivr.net/vast-player/latest/vast-player.min.js:2:14779
    at Array.map (native)
    at Function.b.exports [as pojoFromXML] (https://cdn.jsdelivr.net/vast-player/latest/vast-player.min.js:2:14420)
    at https://cdn.jsdelivr.net/vast-player/latest/vast-player.min.js:2:11153
    at Array.<anonymous> (https://cdn.jsdelivr.net/vast-player/latest/vast-player.min.js:1:31598)
    at MutationObserver.c (https://cdn.jsdelivr.net/vast-player/latest/vast-player.min.js:2:2135)
```

Tag is working on JWPlayer as you can see here : http://tools.springserve.com/tagtest

Thanks for help.

**Comment by atghw** [comment]
I guess the provided VAST from springserve.com is not 100% valid ... there is a duplicate/empty creative:

```
...
<Creative sequence="1">
...
</Creative>
<Creative sequence="1"/>   <--- HERE

```

**Comment by LuNiKoFf** [comment]
Thanks, for informations.
